
-- I Generated 10 possible question that can be expected from you Boss, and will be very benificial for the company
-- to understand its customer segment and thier best products


SELECT * FROM customer

--Q1 what is the total revenue generated by male and female customers

SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender

--Q2 which customers used a discount but still spent more than the average purchase amount

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--Q3 which are the top 5 products zith the highest average reviez rating?

SELECT TOP 10
    item_purchased, ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Q4 compare the average purchase amount betzeen standard and express shipping?

SELECT shipping_type,
ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5 do subscribed customers spend more ? compare average spend and total revenue between subscribers and non subs

SELECT subscription_status, 
COUNT(customer_id) AS total_customer,
ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2) AS avg_spend,
ROUND(SUM(CAST(purchase_amount AS FLOAT)), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend

--Q6 which 5 products have the highest percentatge of purchases with discounted applied?

SELECT item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q7 segment customers into new, returning, and loyal based on their total number of previous purchases and show the count of each segment

WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returned'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customer"
FROM customer_type
GROUP BY customer_segment;

--Q8 whate are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
    item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Q9 Are customer's who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10 What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT * FROM dbo.customer;